version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scc_telkom_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:XQ0e8W5iN2XzY2k5bWxvZ3Bxc3R1dnd4eXoxMjM0NTY3ODk=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
